service: margarine

plugins:
  - serverless-domain-manager

frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'dynamodb:Scan'
        - 'dynamodb:GetItem'
      Resource:
        - 'arn:aws:dynamodb:us-east-1:438693460185:table/margarine-posts'

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  getAllPosts:
    handler: bin/getAllPosts
    events:
      - http:
          path: posts
          method: get
  getOnePost:
    handler: bin/getOnePost
    events:
      - http:
          path: posts/{id}
          method: get
          request:
            parameters:
              paths:
                id: true

resources:
  Resources:
    postsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: margarine-posts
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

custom:
  customDomain:
    domainName: 'margarine.marioleone.me'
